name: Build
on: push

jobs:
  npm-build:
    name: npm-build 工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      
      - run: pnpm install
      - run: pnpm build

   